baseURL = "/"
disableLiveReload = true
languageCode = "en-us"
paginate = 25
preserveTaxonomyNames = true
title = "Living Water Evangelical Church"
[[menu.main]]
identifier = "mandarin"
name = "中文"
url = "http://lwechurch.org"
weight = 3
[[menu.main]]
name = "Summer Retreat Registration"
url = "http://lwechurch.org/development/MemberPortal/LoginEN.aspx"
weight = 2
[params]
environment = "production"
