---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/landing-page-section
  label: Landing page section
  create: all
  match: "**/*"
- type: directory
  path: content/staff
  label: Staff
  create: all
  match: "**/*"
- type: directory
  path: content/sermon
  label: Sermon
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
